export type CipSlenderAssetKey =
	| 'logo'
	| 'background'
	| 'menuOrnament'
	| 'contentOrnament'
	| 'themeBoxOrnament'
	| 'topIconTwitch'
	| 'topIconYoutube'
	| 'topIconDownload'
	| 'topIconOnline'
	| 'menuButtonBackground'
	| 'menuButtonHover'
	| 'menuIconNews'
	| 'menuIconCommunity'
	| 'menuIconLibrary'
	| 'menuIconShop'
	| 'menuIconAbout'
	| 'menuIconGameGuides'
	| 'menuIconCharacterTrade'
	| 'menuIconAccount'
	| 'menuIconForum'
	| 'menuIconSupport'
	| 'menuIconActiveSubmenu'
	| 'menuExpandPlus'
	| 'menuExpandMinus'
	| 'menuGreenLight'
	| 'menuLabelNews'
	| 'menuLabelCommunity'
	| 'menuLabelLibrary'
	| 'menuLabelShop'
	| 'menuLabelAbout'
	| 'menuLabelGameGuides'
	| 'menuLabelCharacterTrade'
	| 'menuLabelAccount'
	| 'menuLabelForum'
	| 'menuLabelSupport'
	| 'contentTitleBackground'
	| 'contentCacheTitleBackground'
	| 'contentFrameHorizontal'
	| 'contentFrameVertical'
	| 'contentFrameEdge'
	| 'contentCornerTopLeft'
	| 'contentCornerTopRight'
	| 'contentCornerBottomLeft'
	| 'contentCornerBottomRight'
	| 'contentBorder'
	| 'paperTexture'
	| 'newsHeadlineBackground'
	| 'headlineBracerLeft'
	| 'headlineBracerRight'
	| 'headlineNewsTicker'
	| 'headlineNews'
	| 'newsTickerIconCommunity'
	| 'newsTickerIconDevelopment'
	| 'newsHeadlineIcon'
	| 'boxTop'
	| 'boxBottom'
	| 'boxHeader'
	| 'chain'
	| 'loginButton'
	| 'myAccountButton'
	| 'logoutButton'
	| 'createAccountButton'
	| 'downloadButton'
	| 'shopButton'
	| 'loginBoxBackground'
	| 'loginCreateAccountText'
	| 'loginCreateAccountTextHover'
	| 'smallButtonBackground'
	| 'smallButtonHover'
	| 'mediumButtonBackground'
	| 'mediumButtonHover'
	| 'promoPremiumBox'
	| 'premiumPromoArt'
	| 'premiumCrown'
	| 'premiumOverlay'
	| 'premiumButtonBackground'
	| 'premiumButtonHover'
	| 'promoNetworksBox'
	| 'networkFacebook'
	| 'networkFacebookHover'
	| 'networkYoutube'
	| 'networkYoutubeHover'
	| 'promoNewcomerBox'
	| 'promoTrailerBox'
	| 'trailerPreview'
	| 'trailerPreviewHover'
	| 'promoScreenshotBox'
	| 'promoScreenshotFrame'
	| 'promoScreenshotImage'
	| 'promoPollBox'
	| 'rightTopper'
	| 'rightStatue'
	| 'rightCreature'
	| 'rightBoss';

export type CipSlenderAssets = Partial<Record<CipSlenderAssetKey, string>> &
	Record<string, string | undefined>;

export function cipAsset(
	assets: Record<string, string | undefined> | null | undefined,
	key: CipSlenderAssetKey,
): string | null {
	return assets?.[key] ?? null;
}
